footprint: [[0.5, 0.3], [0.5, -0.3], [-0.5, 0.3 ], [-0.5,-0.3]]
#robot_radius: 0.35
inflation_radius: 0.55
obstacle_range: 3.0
raytrace_range: 3.0
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser_link, data_type: LaserScan, topic: laser_scan, marking: true, clearing: true}
